// .prototype -  A Special Object:  (.prototype) where you can add methods and properties....


// Constructor Function...
function Person(firstName, lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
}

// here, we are adding method to a prototype....
Person.prototype.getFullName = function(){
    return this.firstName + " " + this.lastName;
};

// here, we can create many objects...(use only---->  Person Constructor Function)...

const person1 = new Person("Rohan", "Jaiswal");                 // here, we are adding 1st method.....
const person2 = new Person("Priyanka", "Madhwal");          // here, we are adding 2st method..... 
// we can add many methods...


// here, we are print or use shared method.....
console.log(person1.getFullName());
console.log(person2.getFullName()); 